version: '3.1'

services:

  database:
    image: psql
    restart: always
    build:
      context: db/
    environment:
      POSTGRES_USER: avito
      POSTGRES_PASSWORD: avito
      POSTGRES_DB: avito
    ports:
      - 5432:5432
  url-shortener:
    build: .
    depends_on:
      - database
    container_name: avito_url_shortener
    restart: always
    ports:
      - "8080:8080"
    networks:
      - default
